var testData = {
    "assets":{
        "SC_LeftArrow_up.png":{
            "label":"SC_LeftArrow_up.png",
            "path":"/studio/assets/102777/full/SC_LeftArrow_up.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102777/full/SC_LeftArrow_up.png"
        },
        "SC_LeftArrow_over.png":{
            "label":"SC_LeftArrow_over.png",
            "path":"/studio/assets/102778/full/SC_LeftArrow_over.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102778/full/SC_LeftArrow_over.png"
        },
        "SC_RightArrow_up.png":{
            "label":"SC_RightArrow_up.png",
            "path":"/studio/assets/102779/full/SC_RightArrow_up.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102779/full/SC_RightArrow_up.png"
        },
        "SC_RightArrow_over.png":{
            "label":"SC_RightArrow_over.png",
            "path":"/studio/assets/102780/full/SC_RightArrow_over.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102780/full/SC_RightArrow_over.png"
        },
        "SC_CloseBtn_up.png":{
            "label":"SC_CloseBtn_up.png",
            "path":"/studio/assets/102781/full/SC_CloseBtn_up.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102781/full/SC_CloseBtn_up.png"
        },
        "SC_CloseBtn_over.png":{
            "label":"SC_CloseBtn_over.png",
            "path":"/studio/assets/102782/full/SC_CloseBtn_over.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102782/full/SC_CloseBtn_over.png"
        },
        "SC_CloseBtn_down.png":{
            "label":"SC_CloseBtn_down.png",
            "path":"/studio/assets/102783/full/SC_CloseBtn_down.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102783/full/SC_CloseBtn_down.png"
        },
        "SC_MapMarker_active.png":{
            "label":"SC_MapMarker_active.png",
            "path":"/studio/assets/102784/full/SC_MapMarker_active.png",
            "width":18,
            "height":30,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102784/full/SC_MapMarker_active.png"
        },
        "SC_MapMarker_inactive.png":{
            "label":"SC_MapMarker_inactive.png",
            "path":"/studio/assets/102785/full/SC_MapMarker_inactive.png",
            "width":18,
            "height":30,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102785/full/SC_MapMarker_inactive.png"
        },
        "SC_Loader.gif":{
            "label":"SC_Loader.gif",
            "path":"/studio/assets/118113/full/SC_Loader.gif",
            "width":50,
            "height":50,
            "contentType":"image/gif",
            "defaultLoader":true,
            "url":"https://live-ssl.spongecell.com/studio/assets/118113/full/SC_Loader.gif"
        },
        "frame1":{
            "id":146164,
            "src":"https://assets-ssl.cdn.spongecell.com/images/501098/thumb/300_250_canv-dyn300x250.jpg",
            "src.https":"https://assets-ssl.cdn.spongecell.com/images/501098/thumb/300_250_canv-dyn300x250.jpg",
            "contentType":"image/jpeg",
            "width":300,
            "height":250,
            "url":"https://assets-ssl.cdn.spongecell.com/images/501098/thumb/300_250_canv-dyn300x250.jpg",
            "name":"frame1"
        },
        "background":{
            "id":146165,
            "src":"https://assets-ssl.cdn.spongecell.com/images/501099/thumb/300_250_canv-dyn300x250-bg.jpg",
            "src.https":"https://assets-ssl.cdn.spongecell.com/images/501099/thumb/300_250_canv-dyn300x250-bg.jpg",
            "contentType":"image/jpeg",
            "width":300,
            "height":250,
            "url":"https://assets-ssl.cdn.spongecell.com/images/501099/thumb/300_250_canv-dyn300x250-bg.jpg",
            "name":"background"
        }
    },
    "landingPages":{
        "9359":"http://spongecell.com/?ctaLink",
        "9360":"http://spongecell.com/?bgLink",
        "Creative Landing Page":{
            "id":9336,
            "url":"http://www.spongecell.com?default"
        },
        "backgroundLink":{
            "id":9360,
            "url":"http://www.spongecell.com?background"
        },
        "ctaLink":{
            "id":9359,
            "url":"http://www.spongecell.com?cta"
        }
    },
    "properties":{
        "Name":{
            "text":"Flash Canvas Generic",
            "name":"Name"
        },
        "headline":{
            "text":"Headline",
            "name":"headline"
        },
        "copy":{
            "text":"Body Copy",
            "name":"copy"
        },
        "legal":{
            "text":"In at ligula nec ligula auctor alique. Pellentesque mollis, risus ut porttitor malesuada, nisl ante facilisis mi, maximus finibus lectus enim quis ipsum. Mauris elit ipsum, hendrerit in felis nec, consectetur mollis nulla. Morbi porttitor ultrices nulla non hendrerit. Aliquam fermentum massa at lectus aliquet tincidunt. Maecenas elementum ac lacus ac laoreet.",
            "name":"legal"
        }
    }
};