var testData = {  
    "assets":{  
        "SC_LeftArrow_up.png":{  
            "label":"SC_LeftArrow_up.png",
            "path":"/studio/assets/102777/full/SC_LeftArrow_up.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102777/full/SC_LeftArrow_up.png"
        },
        "SC_LeftArrow_over.png":{  
            "label":"SC_LeftArrow_over.png",
            "path":"/studio/assets/102778/full/SC_LeftArrow_over.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102778/full/SC_LeftArrow_over.png"
        },
        "SC_RightArrow_up.png":{  
            "label":"SC_RightArrow_up.png",
            "path":"/studio/assets/102779/full/SC_RightArrow_up.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102779/full/SC_RightArrow_up.png"
        },
        "SC_RightArrow_over.png":{  
            "label":"SC_RightArrow_over.png",
            "path":"/studio/assets/102780/full/SC_RightArrow_over.png",
            "width":40,
            "height":40,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102780/full/SC_RightArrow_over.png"
        },
        "SC_CloseBtn_up.png":{  
            "label":"SC_CloseBtn_up.png",
            "path":"/studio/assets/102781/full/SC_CloseBtn_up.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102781/full/SC_CloseBtn_up.png"
        },
        "SC_CloseBtn_over.png":{  
            "label":"SC_CloseBtn_over.png",
            "path":"/studio/assets/102782/full/SC_CloseBtn_over.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102782/full/SC_CloseBtn_over.png"
        },
        "SC_CloseBtn_down.png":{  
            "label":"SC_CloseBtn_down.png",
            "path":"/studio/assets/102783/full/SC_CloseBtn_down.png",
            "width":26,
            "height":26,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102783/full/SC_CloseBtn_down.png"
        },
        "SC_MapMarker_active.png":{  
            "label":"SC_MapMarker_active.png",
            "path":"/studio/assets/102784/full/SC_MapMarker_active.png",
            "width":18,
            "height":30,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102784/full/SC_MapMarker_active.png"
        },
        "SC_MapMarker_inactive.png":{  
            "label":"SC_MapMarker_inactive.png",
            "path":"/studio/assets/102785/full/SC_MapMarker_inactive.png",
            "width":18,
            "height":30,
            "contentType":"image/png",
            "defaultLoader":false,
            "url":"https://live-ssl.spongecell.com/studio/assets/102785/full/SC_MapMarker_inactive.png"
        },
        "SC_Loader.gif":{  
            "label":"SC_Loader.gif",
            "path":"/studio/assets/118113/full/SC_Loader.gif",
            "width":50,
            "height":50,
            "contentType":"image/gif",
            "defaultLoader":true,
            "url":"https://live-ssl.spongecell.com/studio/assets/118113/full/SC_Loader.gif"
        },
        "frame1":{  
            "id":146164,
            "src":"https://assets-ssl.cdn.spongecell.com/images/501233/thumb/300_250_edge-dyn300x250_.jpg",
            "src.https":"https://assets-ssl.cdn.spongecell.com/images/501233/thumb/300_250_edge-dyn300x250_.jpg",
            "contentType":"image/jpeg",
            "width":300,
            "height":250,
            "url":"https://assets-ssl.cdn.spongecell.com/images/501233/thumb/300_250_edge-dyn300x250_.jpg",
            "name":"frame1"
        },
        "background":{  
            "id":146165,
            "src":"https://assets-ssl.cdn.spongecell.com/images/501234/thumb/300_250_edge-dyn300x250-bg.jpg",
            "src.https":"https://assets-ssl.cdn.spongecell.com/images/501234/thumb/300_250_edge-dyn300x250-bg.jpg",
            "contentType":"image/jpeg",
            "width":300,
            "height":250,
            "url":"https://assets-ssl.cdn.spongecell.com/images/501234/thumb/300_250_edge-dyn300x250-bg.jpg",
            "name":"background"
        },
        "flash-canvas-api.html":{  
            "label":"flash-canvas-api.html",
            "path":"/studio/assets/150145/original/flash-canvas-api.html",
            "width":null,
            "height":null,
            "contentType":"text/html",
            "defaultLoader":false,
            "children":[  
                {  
                    "path":"/studio/assets/150145/original/assets/background.jpg",
                    "width":300,
                    "height":250,
                    "contentType":"image/jpeg",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/background.jpg"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/easeljs-0.7.1.min.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/easeljs-0.7.1.min.js"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/flash-canvas-api.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/flash-canvas-api.js"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/frame1.png",
                    "width":300,
                    "height":250,
                    "contentType":"image/png",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/frame1.png"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/image1.jpg",
                    "width":301,
                    "height":269,
                    "contentType":"image/jpeg",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/image1.jpg"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/movieclip-0.7.1.min.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/movieclip-0.7.1.min.js"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/preloadjs-0.4.1.min.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/preloadjs-0.4.1.min.js"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/spongeapi.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/spongeapi.js"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/spongecell.png",
                    "width":300,
                    "height":250,
                    "contentType":"image/png",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/spongecell.png"
                },
                {  
                    "path":"/studio/assets/150145/original/assets/tweenjs-0.5.1.min.js",
                    "width":null,
                    "height":null,
                    "contentType":"text/javascript",
                    "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/assets/tweenjs-0.5.1.min.js"
                }
            ],
            "url":"https://live-ssl.spongecell.com/studio/assets/150145/original/flash-canvas-api.html"
        }
    },
    "landingPages":{  
        "Creative Landing Page":{  
            "id":9336,
            "url":"http://www.spongecell.com"
        },
        "backgroundLink":{  
            "id":9360,
            "url":"http://spongecell.com/?bgLinkEdge"
        },
        "ctaLink":{  
            "id":9359,
            "url":"http://spongecell.com/?ctaLinkEdge"
        }
    },
    "properties":{  
        "Name":{  
            "text":"Edge Animate",
            "name":"Name"
        },
        "headline":{  
            "text":"This is Edge Animate",
            "name":"headline"
        },
        "copy":{  
            "text":"Latoya, Tito, Jermaine.",
            "name":"copy"
        },
        "legal":{  
            "text":"Morbi porttitor ultrices nulla non hendrerit. Aliquam fermentum massa at lectus aliquet tincidunt. Maecenas elementum ac lacus ac laoreet. Integer pharetra mi vel turpis pellentesque convallis. In at ligula nec ligula auctor alique. Pellentesque mollis, risus ut porttitor malesuada, nisl ante facilisis mi, maximus finibus lectus enim quis ipsum. Mauris elit ipsum, hendrerit in felis nec, consectetur mollis nulla. ",
            "name":"legal"
        }
    }
};